### ISSUE TITLE
WS Merged : retour d'un seul PPN et non de plusieurs

### ISSUE THREAD

**Issue by TesteFixe** [abes-esr/abes-webservices#1]
Actuellement, le WebService Merged est susceptible de renvoyer plusieurs PPN pour peu qu'il y ait eu des fusions en "cascade" : A fusionné au profit de B, puis B fusionné au profit de C : l''interrogation sur A renvoie alors : C --PPN actif-- PUIS B --PPN fusionné--.

exemple : https://www.sudoc.fr/services/merged/020250223&format=text/json

Cela génère donc un "array" JSON, là où on attend du WS un object simple -1 seul réponse (le ppn actuellement actif).

https://stp.abes.fr/node/60793/edit?origine=sudocpro
https://twitter.com/27point7/status/1147026797109940227

**Comment by ThomasMic** [comment]
un correctif a été passé en production pour ne retourner que le seul PPN actif, ex https://www.sudoc.fr/services/merged/020250223 retourne maintenant une seule notice ppn 002722011 : 

`<?xml version="1.0" encoding="UTF-8"?>
<sudoc service="merged">
    <query>
        <ppn>020250223</ppn>
        <result>
            <ppn>002722011</ppn>
        </result>
    </query>
</sudoc>`

**Comment by TesteFixe** [comment]
Merci Thomas!
Je me permets de clore alors!!
