### ISSUE TITLE
API Solr IdRef - Problème avec recordtype_z:r (Rameau)

### ISSUE THREAD

**Issue by jajm** [abes-esr/abes-webservices#7]
Bonjour,

Auparavant il était possible d'utiliser le champ `subjectheading_t` pour faire des recherches dans les notices Rameau (`recordtype_z:r`) mais aujourd'hui ce n'est plus possible.

Ex: https://www.idref.fr/Sru/Solr?wt=json&indent=on&q=recordtype_z:r%20AND%20subjectheading_t:bibliotheques
Ne retourne aucun résultat

Les premiers résultats de https://www.idref.fr/Sru/Solr?wt=json&indent=on&q=recordtype_z:r sont des notices de regroupement

**Comment by Francois-Mistral** [comment]
Bonjour,

nous avons fait un peu de ménage dans les types de notice (il nous reste à le documenter).

Le recordtype des notices Rameau est maintenant "j". D'où les requêtes suivantes :

[https://www.idref.fr/Sru/Solr?wt=json&indent=on&q=recordtype_z:j](https://www.idref.fr/Sru/Solr?wt=json&indent=on&q=recordtype_z:j%20AND%20subjectheading_t:bibliotheques)

et

https://www.idref.fr/Sru/Solr?wt=json&indent=on&q=recordtype_z:j%20AND%20subjectheading_t:bibliotheques

Bien à vous.

**Comment by jajm** [comment]
Merci!
